backend:
  name: git-gateway
  branch: main

media_folder: 'public/images/uploads'
public_folder: '/images/uploads'

collections:
  - name: 'pages'
    label: 'Pages'
    files:
      - name: 'home'
        label: 'Home Page'
        file: 'content/pages/home.md'
        fields:
          - {
              label: 'News Section Title',
              name: 'news_title',
              widget: 'string',
              default: 'Practice News & Updates',
            }
          - {
              label: 'News Content',
              name: 'news_content',
              widget: 'markdown',
              default: 'We will be updating our website soon.',
            }
